// Tank Drive
// On this page
// Joystick Ports
//

package org.usfirst.frc0.MyRobot.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc0.MyRobot.OI;
import org.usfirst.frc0.MyRobot.Robot;

/**
 *
 */
public class  TankDrive extends Command {

    public TankDrive() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis)
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    	requires(Robot.driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    	/** 
    	 * This is what you change to reverse the joystick
    	 *  Xbox Controller:
    	 *  Left Y = axis 1 
    	 *  Right Y = axis 5
    	 */
    	
		//Robot.driveTrain.robotDrive(OI.xboxController.getRawAxis(5), OI.xboxController.getRawAxis(1));
		Robot.driveTrain.robotDrive((-1* OI.xboxController.getRawAxis(1)),(-1* OI.xboxController.getRawAxis(5))); 
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
